<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Next_2</name>
   <tag></tag>
   <elementGuidId>05042af8-b9a0-4a8b-94c1-f545a3116103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button#btnnext</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
