<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Lessee_Name_Textfield</name>
   <tag></tag>
   <elementGuidId>303f1952-1126-42e7-943c-e8b7c91d743f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lessee_nm</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
