<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PhoneNumber_TextField</name>
   <tag></tag>
   <elementGuidId>8fe55570-2fc3-498e-a4e8-5df9a28dd352</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phone_a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
