<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search_Document_ID_Textfield</name>
   <tag></tag>
   <elementGuidId>248d4b33-af11-4805-b233-ff1bf4a101a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search_val</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
