<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ALLAGIIDOMLCIMMI</name>
   <tag></tag>
   <elementGuidId>92487449-370a-4c71-8d14-2c705de2b0d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[3]/div/div/select[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>583cf995-ac53-4739-a6e9-21ce11fd3a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>eb3d4f31-0d52-4b28-ae5d-52ecfcd7cfd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ALLAGIIDOMLCIMMI</value>
      <webElementGuid>cb3a6316-8532-4e36-9814-b2fa0f1a545a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;viewpage&quot;]/div[@class=&quot;pagelayout&quot;]/div[@class=&quot;navigasi&quot;]/div[1]/div[@class=&quot;form-inline&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>adaa395a-17f5-466a-9614-9adabed82cb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[3]/div/div/select[2]</value>
      <webElementGuid>ecb420ed-ca0c-419b-a423-c26cbcd1b857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Dokumen Dimusnahkan'])[2]/following::select[2]</value>
      <webElementGuid>d8c3bb54-55d1-4dde-b04c-66bded1dd2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::select[2]</value>
      <webElementGuid>e600831b-1380-4ae7-95fe-60f94744ef27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun Destroyed'])[1]/preceding::select[1]</value>
      <webElementGuid>3a440e78-be4c-47bc-8396-6b1dafad189a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>e7421cbb-148e-4c9d-b77a-f928426ac5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'ALLAGIIDOMLCIMMI' or . = 'ALLAGIIDOMLCIMMI')]</value>
      <webElementGuid>6d2d4f13-1fd3-4384-90bc-2115ac1f1e77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
