<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_JanuariFebruariMaretAprilMeiJuniJuli_13de9b</name>
   <tag></tag>
   <elementGuidId>715f5288-5a6c-42ad-8548-9cf35fbc8db5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Sen'])[1]/preceding::select[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select.flatpickr-monthDropdown-months</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8c41a5eb-81d3-48ff-b8c4-b2ff87fbd9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flatpickr-monthDropdown-months</value>
      <webElementGuid>fa72b866-b97e-478b-9ed7-9b0a33b624a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5cbd6b12-5fac-4f8f-8497-10fff33def8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JanuariFebruariMaretAprilMeiJuniJuliAgustusSeptemberOktoberNovemberDesember</value>
      <webElementGuid>a87b3d5b-a2cf-4b3b-adef-f1eede3950c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;flatpickr-calendar animate showTimeInput open arrowTop&quot;]/div[@class=&quot;flatpickr-months&quot;]/div[@class=&quot;flatpickr-month&quot;]/div[@class=&quot;flatpickr-current-month&quot;]/select[@class=&quot;flatpickr-monthDropdown-months&quot;]</value>
      <webElementGuid>9fad9af4-bfed-4885-b41b-32ba2ac969aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sen'])[1]/preceding::select[1]</value>
      <webElementGuid>349ed4c1-1433-4c1e-86a9-f3fa6363d247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sel'])[1]/preceding::select[1]</value>
      <webElementGuid>6906a100-e848-4ecd-9564-c2a8308a4fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/select</value>
      <webElementGuid>f5a54a5a-59a1-4738-b660-53a6f5a23f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'JanuariFebruariMaretAprilMeiJuniJuliAgustusSeptemberOktoberNovemberDesember' or . = 'JanuariFebruariMaretAprilMeiJuniJuliAgustusSeptemberOktoberNovemberDesember')]</value>
      <webElementGuid>8631ceee-9af1-412e-94fe-6453aa7c8300</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
