<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Yes</name>
   <tag></tag>
   <elementGuidId>4d88bdd7-7816-4cfb-a8ba-5bb8f058c57a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#yes</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
