<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ParentTable</name>
   <tag></tag>
   <elementGuidId>78a9f586-eb97-45cb-9c62-015e42c1cf60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
