<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Regulation_SOP_View_Close</name>
   <tag></tag>
   <elementGuidId>f3a4b43d-0b58-4273-add1-16a94bc4e7d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.close</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
