<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>12_closepage</name>
   <tag></tag>
   <elementGuidId>fdef7723-3f2e-497f-9ee0-a5dd3b4426e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.fa-sign-out</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
