<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>8_continue</name>
   <tag></tag>
   <elementGuidId>e9273cc0-3096-4e2c-a43e-69064a560723</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.swal2-confirm</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
