<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>9_continue-yes</name>
   <tag></tag>
   <elementGuidId>43094bd0-a8e8-4362-92fb-073786e9a0bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.swal2-confirm</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
