<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>3_login</name>
   <tag></tag>
   <elementGuidId>3b6e8df3-a349-4473-ae52-2ddb162b4a16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_login</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
