<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Beneficial_Owner_Type_RadioButton</name>
   <tag></tag>
   <elementGuidId>4faf7b11-2af6-43da-ad63-2cad40894f00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#botyes</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
