<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Beneficial_Owner_Availability_RadioButton</name>
   <tag></tag>
   <elementGuidId>36fbe567-71e9-40a9-940a-f828e3582f9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#owner_avail</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
