<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Contract_Type_Dropdown</name>
   <tag></tag>
   <elementGuidId>061a1a15-4704-4dab-9a41-836cd268f3fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select#con_type</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
