<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Customer_Type_RadioButton</name>
   <tag></tag>
   <elementGuidId>406b7ddb-9d8b-4589-a528-0dcadfd800cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#Corp</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
