<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Finace_Type_Dropdown</name>
   <tag></tag>
   <elementGuidId>e9abcd88-bd6c-45bf-b643-830518cd65bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select#fin_type</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
