<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Go_Public_RadioButton</name>
   <tag></tag>
   <elementGuidId>ca7224e8-c25d-426d-bd29-3c02b3f086e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#publicno</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
