<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Purpose_Of_Finace_Dropdown</name>
   <tag></tag>
   <elementGuidId>ade9025d-7d97-4411-a55a-76d4bc6ff9b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select#PURPOFFINC</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
