<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Vehicle_Condition_RadioButton</name>
   <tag></tag>
   <elementGuidId>d047d92b-7921-42ab-9c6b-881e794b3cce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#used</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
