<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Amortization Report</name>
   <tag></tag>
   <elementGuidId>ddbc0d35-d21b-425e-9702-051083956da9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='treemenu2']/li/ul/li[3]/ul/li[6]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>94c768ee-e117-44cc-93df-0693ad8040b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>module_cam/rpt_amortization.php?menu_id=1.4.7.2</value>
      <webElementGuid>e7488667-82a7-4cf3-abd9-9e5fef619e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>main1</value>
      <webElementGuid>1918f537-9307-4d41-9272-f06ebd63d472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Amortization Report</value>
      <webElementGuid>2ab8f8bc-f262-47df-b91b-c73827ab549a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treemenu2&quot;)/li[@class=&quot;submenu&quot;]/ul[1]/li[@class=&quot;submenu&quot;]/ul[1]/li[@class=&quot;submenu&quot;]/ul[1]/li[2]/a[1]</value>
      <webElementGuid>942b14c9-9f0d-4f16-b6eb-4398b5891a46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='treemenu2']/li/ul/li[3]/ul/li[6]/ul/li[2]/a</value>
      <webElementGuid>c645111b-b6c7-4af9-911e-151c4fd1fe7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Amortization Report')]</value>
      <webElementGuid>35ec8ccd-b835-49f0-8b96-2c0f0029b352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History Payment'])[1]/following::a[1]</value>
      <webElementGuid>c0f05687-57d2-483e-b23b-84eff07a7ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Undisburse Contract'])[1]/preceding::a[1]</value>
      <webElementGuid>0dbb1184-1b93-4706-a4c9-64f25c0c636e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Amortization Report']/parent::*</value>
      <webElementGuid>71744ad1-9de2-44c0-81d4-a75e3876eb5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'module_cam/rpt_amortization.php?menu_id=1.4.7.2')]</value>
      <webElementGuid>197c9197-c761-4e87-8aac-07fe66bbe09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li[2]/a</value>
      <webElementGuid>1cccef2e-a363-4e82-bf8d-c6913e97f8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'module_cam/rpt_amortization.php?menu_id=1.4.7.2' and (text() = 'Amortization Report' or . = 'Amortization Report')]</value>
      <webElementGuid>d792b7dc-6b95-4fe7-96f9-b9d9318a0a5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
