<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dealer Profile</name>
   <tag></tag>
   <elementGuidId>edad1c8e-f58f-49d3-bb66-b3611561c965</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='treemenu2']/li[5]/ul/li[2]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e7797bf5-6164-4941-a693-0a71e05d45c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>module_other/rpt_dealer_profile.php?menu_id=6.2.4</value>
      <webElementGuid>29185369-78ed-4371-935c-f4c9488e4a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>main1</value>
      <webElementGuid>58657067-897d-44cb-8501-b37e9f44dcd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dealer Profile</value>
      <webElementGuid>f82e60d6-0afb-405f-b9bf-97d91491cf27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treemenu2&quot;)/li[@class=&quot;submenu&quot;]/ul[1]/li[@class=&quot;submenu&quot;]/ul[1]/li[3]/a[1]</value>
      <webElementGuid>bb6f981f-0fc0-4bc9-887f-6098304c3305</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='treemenu2']/li[5]/ul/li[2]/ul/li[3]/a</value>
      <webElementGuid>b29e463b-f6a1-4742-86df-a201f734c6cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dealer Profile')]</value>
      <webElementGuid>00744f2b-de1d-4135-9773-2af55441dede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List of Supplier'])[1]/following::a[1]</value>
      <webElementGuid>ab26918f-ecb9-4152-bff8-a8c48d3d1a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dealer'])[1]/following::a[2]</value>
      <webElementGuid>ac6dc4b8-0324-46ac-927e-098dbd1d9a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model'])[1]/preceding::a[1]</value>
      <webElementGuid>bc1f604d-342a-4c8d-89a5-a2a0e48c0291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dealer Profile']/parent::*</value>
      <webElementGuid>74027e5e-af28-488c-9ab7-08380bda9988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'module_other/rpt_dealer_profile.php?menu_id=6.2.4')]</value>
      <webElementGuid>792eda74-17cc-451d-9f98-5b80d3abd7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li[2]/ul/li[3]/a</value>
      <webElementGuid>48412e23-0192-495e-8adb-9527477d5c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'module_other/rpt_dealer_profile.php?menu_id=6.2.4' and (text() = 'Dealer Profile' or . = 'Dealer Profile')]</value>
      <webElementGuid>60ede9a5-978e-43a4-a66f-fd1248711131</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
