<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dealer Profile</name>
   <tag></tag>
   <elementGuidId>80eef4b2-96d8-4917-825a-9e66023fc7ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='treemenu2']/li[5]/ul/li[2]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9f704194-6261-4943-89c9-b262067c88d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>module_other/rpt_dealer_profile.php?menu_id=6.2.4</value>
      <webElementGuid>35ce22f2-d8ed-48c6-b9af-90bb6d2fd0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>main1</value>
      <webElementGuid>75220251-80f7-4a46-b7d8-c2daffbc44d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dealer Profile</value>
      <webElementGuid>f1986d25-f557-4e86-80fe-d24ca3e777fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treemenu2&quot;)/li[@class=&quot;submenu&quot;]/ul[1]/li[@class=&quot;submenu&quot;]/ul[1]/li[3]/a[1]</value>
      <webElementGuid>7c839bbf-d20c-4b44-8315-c3a87ff42e3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='treemenu2']/li[5]/ul/li[2]/ul/li[3]/a</value>
      <webElementGuid>8ddc9e15-03e8-4c2e-9b0f-15613a76fa6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dealer Profile')]</value>
      <webElementGuid>d8a2a74d-cdc8-45d6-ad0e-57dd245826e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List of Supplier'])[1]/following::a[1]</value>
      <webElementGuid>11bb9150-23d2-4230-8aac-699bc0d8d562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dealer'])[1]/following::a[2]</value>
      <webElementGuid>4cb0a872-8382-4f25-9962-795fcd799190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model'])[1]/preceding::a[1]</value>
      <webElementGuid>10a79363-112a-4de8-8c91-2c55e52a4f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dealer Profile']/parent::*</value>
      <webElementGuid>fd5a2e87-664d-4302-bc84-7c2b6b100ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'module_other/rpt_dealer_profile.php?menu_id=6.2.4')]</value>
      <webElementGuid>29f67145-9227-4d6c-aa57-ff6fde2940c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li[2]/ul/li[3]/a</value>
      <webElementGuid>13d3bc8c-f7c8-4925-8dfa-91cbc2cf4dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'module_other/rpt_dealer_profile.php?menu_id=6.2.4' and (text() = 'Dealer Profile' or . = 'Dealer Profile')]</value>
      <webElementGuid>40cb82ac-fc32-4764-880c-1306c37b644e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
