<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LOGOUT</name>
   <tag></tag>
   <elementGuidId>4bcd9045-4c49-48ab-8b9d-6c14ad419e71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'LOGOUT')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b4400b05-4c06-4cba-9dc7-8db7c78b8a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>logout.php?log=1</value>
      <webElementGuid>2c6e0eb9-18cb-4a39-8fda-570c87c6bd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGOUT</value>
      <webElementGuid>08925399-c888-48e0-a295-db108dbb16bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[1]/tbody[1]/tr[2]/td[2]/span[1]/a[1]</value>
      <webElementGuid>fa0bc3ad-1749-4282-ae0a-85148e2a884c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'LOGOUT')]</value>
      <webElementGuid>e374ea30-3278-4fa3-8633-2c6c004f8917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INTERNAL MEMORANDUM'])[1]/following::a[1]</value>
      <webElementGuid>3e133608-3300-4d65-801a-44be38c3724e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/html[1]/body[1]/table[1]/tbody[1]/tr[2]/td[2]/span[1]/a[1]'])[1]/preceding::a[1]</value>
      <webElementGuid>eecb6598-884d-4839-9f50-118d1dc040f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LOGOUT']/parent::*</value>
      <webElementGuid>3237565a-8319-4bd9-b387-4edc82774028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'logout.php?log=1')]</value>
      <webElementGuid>ebf1ae9f-bec2-464a-bc66-7051c9012243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>e68c3c72-94a9-4710-866a-a78c84baa6ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'logout.php?log=1' and (text() = 'LOGOUT' or . = 'LOGOUT')]</value>
      <webElementGuid>c7ca9100-ecb3-4668-980a-d2b0e2c42e0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
