<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Model</name>
   <tag></tag>
   <elementGuidId>803db6af-1afd-4329-b66d-70aaa6f5b039</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='treemenu2']/li[5]/ul/li[3]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f396260f-eb7d-4bec-a8ed-d025042f4cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>module_other/model_entry.php?menu_id=6.3.1</value>
      <webElementGuid>6b2f62bf-3417-4803-bd4b-4aa63f59828a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>main1</value>
      <webElementGuid>c29631e9-01d9-445d-a959-04948cd08804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Model</value>
      <webElementGuid>2a0f0d88-bf7a-4c82-ac8b-979e50fb516c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treemenu2&quot;)/li[@class=&quot;submenu&quot;]/ul[1]/li[@class=&quot;submenu&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>9f7c8058-1bf4-45a2-ac1a-d6820f40aeb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='treemenu2']/li[5]/ul/li[3]/ul/li/a</value>
      <webElementGuid>d2e6de42-2587-4e07-97e3-eef2039ae94f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Model')]</value>
      <webElementGuid>589278f3-f883-43be-a01b-d613a7a33b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dealer Profile'])[1]/following::a[1]</value>
      <webElementGuid>32eba78d-f323-4458-924c-24ac9dc877fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Karoseri'])[1]/preceding::a[1]</value>
      <webElementGuid>c370fcc2-501a-4eb4-ab8a-02408d6310db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand - Type'])[1]/preceding::a[2]</value>
      <webElementGuid>a0298ba0-7c62-498c-9855-79af5efed17d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Model']/parent::*</value>
      <webElementGuid>6f4b7ffc-9fd6-46fd-8ee2-d744769a9580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'module_other/model_entry.php?menu_id=6.3.1')]</value>
      <webElementGuid>f7dcf716-ac27-47e8-9a8f-c39748935131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li[3]/ul/li/a</value>
      <webElementGuid>9b692c2c-f39d-4b35-a9dc-285c317683c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'module_other/model_entry.php?menu_id=6.3.1' and (text() = 'Model' or . = 'Model')]</value>
      <webElementGuid>70e5d778-8904-4ddf-835d-e733ceca9afd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
