<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Model</name>
   <tag></tag>
   <elementGuidId>3a3af24d-8bcc-4499-8ab9-a7c8bb35d6bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='treemenu2']/li[5]/ul/li[3]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>595bc5e7-3423-4dd1-9302-7d48157a95ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>module_other/model_entry.php?menu_id=6.3.1</value>
      <webElementGuid>4f39da51-f34c-4518-8caa-b5b70f8313bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>main1</value>
      <webElementGuid>c919bc8c-4bf1-4d03-acfa-cc0dfda61ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Model</value>
      <webElementGuid>5ada1795-6057-4c23-b3b1-2e17caa83994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treemenu2&quot;)/li[@class=&quot;submenu&quot;]/ul[1]/li[@class=&quot;submenu&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>de45cfe1-9547-4cd3-ab5c-6fa2a14bb58c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='treemenu2']/li[5]/ul/li[3]/ul/li/a</value>
      <webElementGuid>c999e8ff-2326-4041-a80e-104a0080003d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Model')]</value>
      <webElementGuid>6225f772-bc31-44f3-abdc-c07cdb27f2c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dealer Profile'])[1]/following::a[1]</value>
      <webElementGuid>becfb952-d5de-4547-a23b-df0af37b99a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Karoseri'])[1]/preceding::a[1]</value>
      <webElementGuid>bc3a4582-20a4-4ccd-b3c6-124e72ded5af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand - Type'])[1]/preceding::a[2]</value>
      <webElementGuid>97cd8a5a-cac5-4cd8-9b06-d7a13999ce65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Model']/parent::*</value>
      <webElementGuid>382967d5-d26f-44e7-bbdc-e40e45004f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'module_other/model_entry.php?menu_id=6.3.1')]</value>
      <webElementGuid>a4cdb5e3-3fa3-41e8-a534-c99aa08f00ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li[3]/ul/li/a</value>
      <webElementGuid>ee545a39-1479-465c-833e-4457136afd7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'module_other/model_entry.php?menu_id=6.3.1' and (text() = 'Model' or . = 'Model')]</value>
      <webElementGuid>c43d58a1-649a-450b-96af-a18edc59411f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
