<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Report of Rejected Restructuring Covid 19</name>
   <tag></tag>
   <elementGuidId>04b037e5-9e56-45e4-9db3-864677fdd818</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#treemenu2 > li.submenu > ul > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='treemenu2']/li[2]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c653e1de-186b-4621-8999-30bb29c291f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>module_cam/list_report.php?menu_id=3.4</value>
      <webElementGuid>29477325-7ad4-41ff-9711-10f82f306b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>main1</value>
      <webElementGuid>7cb2df82-d934-4f58-aa64-143d76d65a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Report of Rejected Restructuring Covid 19</value>
      <webElementGuid>0bcc55f4-6dc5-4b9d-b066-b8f143055320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treemenu2&quot;)/li[@class=&quot;submenu&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>5f01dbda-3047-400b-a402-3728eb32abd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='treemenu2']/li[2]/ul/li/a</value>
      <webElementGuid>784b4d6a-0373-4a25-95a7-d04a7ec2151e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Report of Rejected Restructuring Covid 19')]</value>
      <webElementGuid>63d9f877-1e15-47cd-8335-83a7f97880e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Undisburse Contract'])[1]/following::a[1]</value>
      <webElementGuid>05e95899-15ae-472c-bac7-5b6538e12d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View IM Restructuring'])[1]/preceding::a[1]</value>
      <webElementGuid>dd13254b-6981-49e4-b6fd-c1a03ef7254a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Report of Rejected Restructuring Covid 19']/parent::*</value>
      <webElementGuid>6275a2df-d3d6-454d-baa3-7f734138ea6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'module_cam/list_report.php?menu_id=3.4')]</value>
      <webElementGuid>bdf2e3dc-ec63-4bb5-a3e1-8a11f2312116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/ul/li[2]/ul/li/a</value>
      <webElementGuid>6f56b187-692b-4b63-84c8-18ea785faa00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'module_cam/list_report.php?menu_id=3.4' and (text() = 'Report of Rejected Restructuring Covid 19' or . = 'Report of Rejected Restructuring Covid 19')]</value>
      <webElementGuid>8f204b1f-2098-4ae5-bc7c-19aa3dccc3ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
