<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View IM Restructuring</name>
   <tag></tag>
   <elementGuidId>c24fc2fd-954b-450a-b365-9371ff0337d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='treemenu2']/li[2]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0c8053c2-f664-4227-b6f5-58ab3f0e9af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>module_cam/view_restructuring.php?menu_id=3.5</value>
      <webElementGuid>8ac8799f-b4e0-4f1b-bbaa-8a6d5c4dc4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>main1</value>
      <webElementGuid>df68efd3-607c-40de-8c19-bfdbca26950c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View IM Restructuring</value>
      <webElementGuid>e633fdfe-5c1b-4d7d-81b4-3ee50bd6c3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treemenu2&quot;)/li[@class=&quot;submenu&quot;]/ul[1]/li[2]/a[1]</value>
      <webElementGuid>1681d78b-2ca0-4b48-89f1-aa42d305fae8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='treemenu2']/li[2]/ul/li[2]/a</value>
      <webElementGuid>e9f8c3c5-f0c5-4264-9eca-9cc08694c63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View IM Restructuring')]</value>
      <webElementGuid>8275b576-6087-4665-8282-b9307a82d154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report of Rejected Restructuring Covid 19'])[1]/following::a[1]</value>
      <webElementGuid>a42d5305-4e6c-4b4b-92f0-196f2a3e51b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operation'])[1]/preceding::a[1]</value>
      <webElementGuid>22478264-261c-4dad-8fcc-098f93ee92d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View IM Restructuring']/parent::*</value>
      <webElementGuid>ddda2ecf-649c-420c-aba7-ae95a221e62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'module_cam/view_restructuring.php?menu_id=3.5')]</value>
      <webElementGuid>3d69c9af-d58f-4df0-905c-6501b12ce911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/ul/li[2]/ul/li[2]/a</value>
      <webElementGuid>461855a4-d79a-4429-a07d-9eb2932d97d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'module_cam/view_restructuring.php?menu_id=3.5' and (text() = 'View IM Restructuring' or . = 'View IM Restructuring')]</value>
      <webElementGuid>0a8e6294-f1ba-4182-8e09-9b11bee499e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
