<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>font_I - 111831280</name>
   <tag></tag>
   <elementGuidId>5edcf0c3-dd22-4110-bf51-13bc0079d348</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>font</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='isipayment']/tr/td[2]/a/font</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>8fa81882-26a3-4b32-a9a9-2be1355fb16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I - 111831280 </value>
      <webElementGuid>ff643c8a-6c85-410a-a3ea-3c447a104f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isipayment&quot;)/tr[1]/td[2]/a[1]/font[1]</value>
      <webElementGuid>c7ecf08c-8577-4eee-be0d-5b7a0c08b53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJ_CAM/Page_MLCI - Credit Approval Memorandum/iframe_LOGOUT_main1</value>
      <webElementGuid>87e80675-5e37-42d4-9b54-2e496b7fa8f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='isipayment']/tr/td[2]/a/font</value>
      <webElementGuid>aec48f10-8243-4886-913e-2a78506bfb45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch'])[1]/following::font[1]</value>
      <webElementGuid>d76705b5-5c88-422c-937f-61a6e0e8eb73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::font[1]</value>
      <webElementGuid>d52c2a96-c76b-48df-90e4-45f55a73ad56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AMELIYAH JAYA PERKASA, PT.'])[1]/preceding::font[1]</value>
      <webElementGuid>e928f59f-237c-47e5-ae3c-4a0527965288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ricky Indra'])[1]/preceding::font[1]</value>
      <webElementGuid>cbaabbc4-3317-4c52-acf9-afebab287f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//font</value>
      <webElementGuid>262543b9-d2bf-47a7-afa8-ef1acc9527ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//font[(text() = 'I - 111831280 ' or . = 'I - 111831280 ')]</value>
      <webElementGuid>a7fc1e93-9cae-48b2-bdb8-436eab625e6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
