<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sun_end_dt</name>
   <tag></tag>
   <elementGuidId>e7969c20-10e3-4706-8ecd-e76b966d927e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#end_dt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='end_dt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>555a0567-2471-4f62-904b-fb5572f16195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f344613-0b32-4fe3-b9d2-7bc905c69a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>end_dt</value>
      <webElementGuid>009d98fa-bb8c-4ad0-9a38-a72d5b2077a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>end_dt</value>
      <webElementGuid>e64e2c4a-686c-4d1f-bcc6-e9f32156a63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>g_calendarObject2.closeCalendar(); return isDate(event)</value>
      <webElementGuid>e0067816-d24e-4eb5-9bd4-d86555be317d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>globalnumber</name>
      <type>Main</type>
      <value>139</value>
      <webElementGuid>b3fa1558-d883-4c86-ae44-67ac12da5032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;end_dt&quot;)</value>
      <webElementGuid>992e8188-4394-4a00-a493-16e1439ae1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJ_CAM/Page_MLCI - Credit Approval Memorandum/iframe_LOGOUT_main1</value>
      <webElementGuid>398e488f-8eaa-454e-afcf-d0ca84407f23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='end_dt']</value>
      <webElementGuid>b754a447-dbef-4f3a-b877-c6771fa7015a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>9788e1ae-9f6c-45a1-aae3-cb8563457f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'end_dt' and @id = 'end_dt']</value>
      <webElementGuid>2afeda7a-bbe6-4c60-b0a0-085fb2ab8071</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
