<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Report for Internal_reportfilter</name>
   <tag></tag>
   <elementGuidId>2b197451-0567-430c-ab29-29589942494c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reportint</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reportint']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b84bf1a8-c0f0-4a67-8310-8664dc2ad0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c24fc223-b653-4223-967e-be729ee73f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reportint</value>
      <webElementGuid>d7548fa3-793f-4c45-918e-5e2e95ab1198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reportfilter</value>
      <webElementGuid>4432d63e-d9da-43e4-a3ff-243404f9dec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>88</value>
      <webElementGuid>705362ca-0820-4868-a82c-2429fd1afe64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reportint&quot;)</value>
      <webElementGuid>286d9b87-afb6-4b44-a940-10cc8375da8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJ_CAM/Page_MLCI - Credit Approval Memorandum/iframe_LOGOUT_main1</value>
      <webElementGuid>8259e5ce-fdf0-4b02-bca4-622f680939cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reportint']</value>
      <webElementGuid>0f74ecb0-2533-4d77-b57a-5ce4c7f5e005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>6379f8b9-0f46-46a4-96bb-10fd11076e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'reportint' and @name = 'reportfilter']</value>
      <webElementGuid>fe78e306-2a8e-42b4-92bd-d9d6a918d498</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
