<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rejected Period -_start_dt</name>
   <tag></tag>
   <elementGuidId>69925a40-09b4-461c-9783-2fa9f1ea5405</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#start_dt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='start_dt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1329ae7a-6efb-4883-a51d-4a179c3bafea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4eb76097-dbec-4e86-a24a-cf7541c1205c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>start_dt</value>
      <webElementGuid>638786df-9654-4653-89b8-e07ef9514671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>start_dt</value>
      <webElementGuid>a38b5332-6698-4000-9fff-69ed20908d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>g_calendarObject1.closeCalendar(); return isDate(event)</value>
      <webElementGuid>500f26ce-4bd0-4a4f-bbba-0dcfbc6bbe60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>globalnumber</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>5019fc09-46c2-4cbd-bcd1-f2ebce78b9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;start_dt&quot;)</value>
      <webElementGuid>27051ec9-b518-4f99-aca9-645f4e43ecea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJ_CAM/Page_MLCI - Credit Approval Memorandum/iframe_LOGOUT_main1</value>
      <webElementGuid>038fb75e-ec9e-4d78-95c9-957ffaa3bd4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='start_dt']</value>
      <webElementGuid>acd64be0-0a76-4d56-ba8d-0b3a636971b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ece96232-d4bb-4d84-9fbe-d1075c42c94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'start_dt' and @id = 'start_dt']</value>
      <webElementGuid>d4318049-9a03-4021-8940-ffda7d7d0210</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
