<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Report for Internal_reportfilter</name>
   <tag></tag>
   <elementGuidId>463c1074-2097-4842-ad7f-8a73bf8a03fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reportint</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reportint']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c42e3df9-cb7e-4a64-b928-a7b483a2f3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>556d34a4-88b9-45da-b7b2-1f5a55bf6cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reportint</value>
      <webElementGuid>8c4b78bc-714d-4b80-8401-46a0d0833de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reportfilter</value>
      <webElementGuid>412b5b02-a67d-44b5-9654-3c8e8979876c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>88</value>
      <webElementGuid>75d735b9-6537-40fc-a4a2-f74cf1196629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reportint&quot;)</value>
      <webElementGuid>ccaf380b-da92-487b-aa3d-a1a40b4aca36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJ_CAM/Page_MLCI - Credit Approval Memorandum/iframe_LOGOUT_main1</value>
      <webElementGuid>b24ee4e2-fc62-4d97-8135-f0828793e2b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reportint']</value>
      <webElementGuid>f19a1747-108d-4bd5-87a7-d04ab79ea0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>10b328fc-eed1-48ea-b549-68d6ebd8091c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'reportint' and @name = 'reportfilter']</value>
      <webElementGuid>db0cc59c-20d9-4e02-8fd5-b5fbb895a78f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
