<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rejected Period -_start_dt</name>
   <tag></tag>
   <elementGuidId>0c379152-429a-49bd-a1e6-88d5da4dfbc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#start_dt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='start_dt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a43a42c-3753-47ed-ac3c-054ec9871418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa0ce63b-40ec-4b65-9a5c-ae5ad3011772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>start_dt</value>
      <webElementGuid>b5097f1f-d54c-4d1b-b276-a9cf6d2c9daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>start_dt</value>
      <webElementGuid>276485cf-4dae-49bd-984b-cf60f94774c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>g_calendarObject1.closeCalendar(); return isDate(event)</value>
      <webElementGuid>6aa9e929-b610-4b63-8ef0-2cec79688d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>globalnumber</name>
      <type>Main</type>
      <value>790</value>
      <webElementGuid>fa306138-d164-4fc7-88a8-1961fa2dfdff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;start_dt&quot;)</value>
      <webElementGuid>5c5e8bde-82a7-4eb3-81e6-05b6c82f8270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJ_CAM/Page_MLCI - Credit Approval Memorandum/iframe_LOGOUT_main1</value>
      <webElementGuid>e55bc69b-2570-472b-95f8-86db105f99be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='start_dt']</value>
      <webElementGuid>389fcf8b-db6c-4c65-8f86-a535a7760cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>00dc4c5d-95b9-4265-bcd8-fd006e15bb65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'start_dt' and @id = 'start_dt']</value>
      <webElementGuid>53592e0d-1e71-46f5-b88d-57f1f5d1e218</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
