<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__contract</name>
   <tag></tag>
   <elementGuidId>04c6a754-1110-4f35-8f52-c33f2a75ab48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contract</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contract']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5545c50c-c9e6-489f-9d20-d9f10259e117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ecd02b1-f163-4e2b-9e4f-33c7b3f823b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contract</value>
      <webElementGuid>e034d6d2-ab96-41f9-8355-26354aecb93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contract</value>
      <webElementGuid>c5cfdfdc-2422-4f3f-87e8-1efc39e633ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isNumberKey(event)</value>
      <webElementGuid>c1d1e158-899c-4cde-a2ed-22994b7ec4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>4f1fa4f1-1500-4203-bc7c-9fee08fb98ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>0a60dcd0-7cb6-47db-9bfa-c01399989fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a9bf2aa1-459f-48ac-bfe0-199cc301d344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contract&quot;)</value>
      <webElementGuid>17d9a395-f5fe-466e-847e-f67fe6124ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJ_CAM/Page_MLCI - Credit Approval Memorandum/iframe_LOGOUT_main1</value>
      <webElementGuid>47bc95dd-1bcd-4fc7-9579-4ef28ed7945b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contract']</value>
      <webElementGuid>423d2f02-d520-460e-a8de-63530cc4e5f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>1f213f7c-7858-4fd6-8586-4ea845e1c5c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>2bc3ed3c-d7d0-4d5c-86bf-ebff7c37a21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'contract' and @id = 'contract']</value>
      <webElementGuid>7012c407-929e-4ce3-8e1b-0b914923e6f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
