<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sun_end_dt</name>
   <tag></tag>
   <elementGuidId>c8f369f5-0be0-4eba-af60-baa388d2eb6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#end_dt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='end_dt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44c163b4-5df9-4cf9-af37-3b58731e0677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05ecabfd-7458-4054-8933-d87430709787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>end_dt</value>
      <webElementGuid>1a789982-d833-4d9b-b7dd-1fa6e9f72af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>end_dt</value>
      <webElementGuid>5c1036f1-fb49-4aa2-9607-553acc1dcd1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>g_calendarObject2.closeCalendar(); return isDate(event)</value>
      <webElementGuid>54eb5fcd-7cb1-49da-bcbf-cf41774aaa7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>globalnumber</name>
      <type>Main</type>
      <value>58</value>
      <webElementGuid>591c00ed-eb90-4638-b15a-ee624069fa49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;end_dt&quot;)</value>
      <webElementGuid>9ca21fcd-29dc-4af1-9a8d-c047cae11772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJ_CAM/Page_MLCI - Credit Approval Memorandum/iframe_LOGOUT_main1</value>
      <webElementGuid>6e4b24aa-47a6-4863-8df7-c027f02940ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='end_dt']</value>
      <webElementGuid>3fdd647e-20cb-418b-82bf-19bcfe62f5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>a94c282c-be6c-47da-9c0b-7d32bf1f696e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'end_dt' and @id = 'end_dt']</value>
      <webElementGuid>0ef4bb7c-e253-4feb-9bae-1dac4a7e5837</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
