<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_111831280--AMELIYAH JAYA PERKASA, PT. Re_8fd222</name>
   <tag></tag>
   <elementGuidId>6538dca3-6df4-4d1d-9382-7be8f371150b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-176</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='ui-id-176']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>afedc984-afc5-436d-991f-bab9390b4515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item ui-state-focus</value>
      <webElementGuid>84bacb1d-97d4-4040-9520-810f4d645b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-176</value>
      <webElementGuid>b5837560-bc32-4215-9e17-e486305fa707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b3b0944a-981c-4b4b-901e-1922616ce987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>111831280--AMELIYAH JAYA PERKASA, PT. Restructuring ke:1</value>
      <webElementGuid>a52c496e-1904-4297-a78e-f756baa817af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-176&quot;)</value>
      <webElementGuid>7cfe9050-4303-4fd3-8a08-78cba55d84bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJ_CAM/Page_MLCI - Credit Approval Memorandum/iframe_LOGOUT_main1</value>
      <webElementGuid>2dec54c4-b69d-4034-a73e-d39c015bd90b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='ui-id-176']</value>
      <webElementGuid>07c119cd-82e7-4d65-adfd-ae320d16f102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-1']/li</value>
      <webElementGuid>7f925a5d-44fb-47b5-bc55-40bca27fbd3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch'])[1]/following::li[1]</value>
      <webElementGuid>d17d2495-4ed3-4b10-9187-70cdb7897f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::li[1]</value>
      <webElementGuid>7c39dd3f-41f5-429f-a442-81662353a050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ui-id-176', '&quot;', ')')])[1]/preceding::li[2]</value>
      <webElementGuid>3f99917b-aaf3-40ef-973d-4ff2c5084ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='111831280--AMELIYAH JAYA PERKASA, PT. Restructuring ke:1']/parent::*</value>
      <webElementGuid>6037e660-ce45-4c56-9787-98b78a2f0c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>f21101c5-3165-407a-bed1-b055d63f3e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ui-id-176' and (text() = '111831280--AMELIYAH JAYA PERKASA, PT. Restructuring ke:1' or . = '111831280--AMELIYAH JAYA PERKASA, PT. Restructuring ke:1')]</value>
      <webElementGuid>38227370-1123-4522-9de2-58a3cd614f8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
