<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_111831280--AMELIYAH JAYA PERKASA, PT. Re_8fd222</name>
   <tag></tag>
   <elementGuidId>3bf01297-6178-4579-ab2e-9191d319c1f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-379</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='ui-id-379']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>19650cbc-84f7-4bc8-abc5-5908a495c82b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item ui-state-focus</value>
      <webElementGuid>737a6a3e-af7c-457e-96ef-00b48ed8540c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-379</value>
      <webElementGuid>f5f71da5-05d5-49e1-8f20-6bc71b7fecdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4f5ba4df-85d5-4ca2-ba80-0ce428cf78f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>111831280--AMELIYAH JAYA PERKASA, PT. Restructuring ke:1</value>
      <webElementGuid>1b315113-f397-4234-aa5d-5c7aa3edd3e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-379&quot;)</value>
      <webElementGuid>60b72902-b0f4-487b-9976-e86c3be827d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJ_CAM/Page_MLCI - Credit Approval Memorandum/iframe_LOGOUT_main1</value>
      <webElementGuid>5aa368b1-783e-4177-a8a6-fd074b1a9038</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='ui-id-379']</value>
      <webElementGuid>98f7bc63-4488-44f4-8d1e-018d45740521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-1']/li</value>
      <webElementGuid>e97bdeeb-3153-4620-af86-994bf207d013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch'])[1]/following::li[1]</value>
      <webElementGuid>3b5758e6-f7c4-40a3-b911-08abf04aa413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::li[1]</value>
      <webElementGuid>446c2da2-19c7-4b35-bc10-25bb31b5d6c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ui-id-379', '&quot;', ')')])[1]/preceding::li[2]</value>
      <webElementGuid>1f317054-a625-4de7-813d-4fcff815ed24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='111831280--AMELIYAH JAYA PERKASA, PT. Restructuring ke:1']/parent::*</value>
      <webElementGuid>084e03f6-b443-4920-b5d6-28b901987e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>7bdf694c-7e5a-445f-827b-fa26c7de68aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ui-id-379' and (text() = '111831280--AMELIYAH JAYA PERKASA, PT. Restructuring ke:1' or . = '111831280--AMELIYAH JAYA PERKASA, PT. Restructuring ke:1')]</value>
      <webElementGuid>52639fef-fb78-4a31-99d4-5e55939f3131</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
