<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_APPROVER AVAILABILITYOperationBranch Man_e15654</name>
   <tag></tag>
   <elementGuidId>6d3a33f0-040f-4e4f-90ab-298a232d4f00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='treemenu2']/li[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>87526c26-4348-45f8-afaa-71b1539927c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submenu</value>
      <webElementGuid>e5ebe9b4-5084-4d0b-a7fe-aefe399c623d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>APPROVER AVAILABILITYOperationBranch ManagerCredit CommiteeCredit Reviewer RequestCredit Reviewer Head Request</value>
      <webElementGuid>ed6973c4-a05b-4c14-ac2a-c0d43de17577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treemenu2&quot;)/li[@class=&quot;submenu&quot;]</value>
      <webElementGuid>70c0a0c2-e33b-4261-ba57-670a8b66b7bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='treemenu2']/li[3]</value>
      <webElementGuid>57e988b7-dfb8-461f-98c9-6ad03d1f4645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View IM Restructuring'])[1]/following::li[1]</value>
      <webElementGuid>c2df2b28-f29e-4a08-a2e0-dc9ffceee37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report of Rejected Restructuring Covid 19'])[1]/following::li[2]</value>
      <webElementGuid>9ca4a05b-c0ff-4043-be80-3c976c1ebf9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='APPROVER AVAILABILITY']/parent::*</value>
      <webElementGuid>7845b87f-d092-4f74-94a6-cf1e85042828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/ul/li[3]</value>
      <webElementGuid>0dab5073-e9f2-47ac-a8c2-904e56bde53e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'APPROVER AVAILABILITYOperationBranch ManagerCredit CommiteeCredit Reviewer RequestCredit Reviewer Head Request' or . = 'APPROVER AVAILABILITYOperationBranch ManagerCredit CommiteeCredit Reviewer RequestCredit Reviewer Head Request')]</value>
      <webElementGuid>a020e452-fad1-46d6-8871-bd9d92e74ae7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
