<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_DealerDealerList of SupplierDealer Profile</name>
   <tag></tag>
   <elementGuidId>bcddd38c-8f50-4c27-b8b2-eb9cdb15a96a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='treemenu2']/li[5]/ul/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d7ad03d6-3827-4b2e-b263-9e46ced44f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submenu</value>
      <webElementGuid>64765615-af9b-4917-b603-74a86bfbbd36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DealerDealerList of SupplierDealer Profile</value>
      <webElementGuid>b5feefc3-3681-4d0f-901f-d5852a6b5271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treemenu2&quot;)/li[@class=&quot;submenu&quot;]/ul[1]/li[@class=&quot;submenu&quot;]</value>
      <webElementGuid>3d10888e-a9ee-457b-864a-5b287ae51a7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='treemenu2']/li[5]/ul/li[2]</value>
      <webElementGuid>86fe6d60-d6ab-424c-b5e3-9a6dbb04a8f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List of Sales'])[1]/following::li[1]</value>
      <webElementGuid>1d22dc80-1659-42f9-853c-d55d63d45699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales'])[1]/following::li[2]</value>
      <webElementGuid>4bab0c32-0888-4dde-8a61-63e73f47c611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dealer']/parent::*</value>
      <webElementGuid>61d40bf8-3ac8-4d2d-9180-4b67dc647ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/ul/li[5]/ul/li[2]</value>
      <webElementGuid>8afc204f-d729-4c20-a010-8313f512c38c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'DealerDealerList of SupplierDealer Profile' or . = 'DealerDealerList of SupplierDealer Profile')]</value>
      <webElementGuid>93c73ed3-671c-44ef-a4dc-27338b8e63a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
