<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_MASTER DATASalesSalesList of SalesDealer_050409</name>
   <tag></tag>
   <elementGuidId>81749141-966b-4afb-a8b3-fa0923aac767</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='treemenu2']/li[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2addffe1-3af3-475e-ba94-24e9f05d29c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submenu</value>
      <webElementGuid>bbf09a96-7d3f-475b-bfcd-a31caf05a37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MASTER DATASalesSalesList of SalesDealerDealerList of SupplierDealer ProfileCollateral ObjectModelKaroseriBrand - TypeList of BrandList of ModelList of KaroseriInsuranceInsuranceList of InsuranceGROUPEntry &amp; EditGroup ReportList of GroupWATCHLISTEntry &amp; EditReport/ ViewEntry &amp; Edit by CorsecBLACKLISTEntry &amp; EditReport/ViewList Pelaporan Terduga TerorisPEPViewReportHIGH RISK CUSTOMER APU PPTVIEWREPORTSID ReportSummary SID ReportDetail SID ReportIndustry Code</value>
      <webElementGuid>98555e3b-219a-4bd7-b4e5-a0900ccc04fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treemenu2&quot;)/li[@class=&quot;submenu&quot;]</value>
      <webElementGuid>fdc59681-a5c2-416a-adec-972d4750b86e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='treemenu2']/li[5]</value>
      <webElementGuid>22f735e6-7ec2-45b5-82b8-3f4402fd61ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input Offering Letter'])[1]/following::li[1]</value>
      <webElementGuid>a6659928-0d36-4304-b5c7-a4fdcd1c6205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MASTER DATA']/parent::*</value>
      <webElementGuid>461840b8-4cab-4121-8591-ae54ba7a4b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/ul/li[5]</value>
      <webElementGuid>bff01e92-73f5-4de2-b0c3-dcea7d61ba8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'MASTER DATASalesSalesList of SalesDealerDealerList of SupplierDealer ProfileCollateral ObjectModelKaroseriBrand - TypeList of BrandList of ModelList of KaroseriInsuranceInsuranceList of InsuranceGROUPEntry &amp; EditGroup ReportList of GroupWATCHLISTEntry &amp; EditReport/ ViewEntry &amp; Edit by CorsecBLACKLISTEntry &amp; EditReport/ViewList Pelaporan Terduga TerorisPEPViewReportHIGH RISK CUSTOMER APU PPTVIEWREPORTSID ReportSummary SID ReportDetail SID ReportIndustry Code' or . = 'MASTER DATASalesSalesList of SalesDealerDealerList of SupplierDealer ProfileCollateral ObjectModelKaroseriBrand - TypeList of BrandList of ModelList of KaroseriInsuranceInsuranceList of InsuranceGROUPEntry &amp; EditGroup ReportList of GroupWATCHLISTEntry &amp; EditReport/ ViewEntry &amp; Edit by CorsecBLACKLISTEntry &amp; EditReport/ViewList Pelaporan Terduga TerorisPEPViewReportHIGH RISK CUSTOMER APU PPTVIEWREPORTSID ReportSummary SID ReportDetail SID ReportIndustry Code')]</value>
      <webElementGuid>455ea305-4ce2-4269-a2f0-f7f56223815c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
