<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_RESTRUCTURING FOR COVIDReport of Rejecte_ccf5bb</name>
   <tag></tag>
   <elementGuidId>11da192a-6afe-4a8e-a812-b264a71a1584</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='treemenu2']/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>aa985d64-9ccc-489a-b6ea-f00b34fd9279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submenu</value>
      <webElementGuid>6142bf8c-f253-41ff-a5af-ea2e403f4b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RESTRUCTURING FOR COVIDReport of Rejected Restructuring Covid 19View IM Restructuring</value>
      <webElementGuid>082a996c-532e-4b53-bca7-6749d9ec66a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treemenu2&quot;)/li[@class=&quot;submenu&quot;]</value>
      <webElementGuid>080b1720-1c61-46dd-bea6-0e049cf41a98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='treemenu2']/li[2]</value>
      <webElementGuid>860ae876-f9ff-4094-b970-156620b9d6b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Undisburse Contract'])[1]/following::li[1]</value>
      <webElementGuid>44521556-8d1c-4bc2-b8c0-83f3ff028f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amortization Report'])[1]/following::li[2]</value>
      <webElementGuid>b427928e-b1f0-4dc6-84e7-71a959e1afae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='RESTRUCTURING FOR COVID']/parent::*</value>
      <webElementGuid>a4eb1601-cfd3-464b-923b-05ce6d42bc42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/ul/li[2]</value>
      <webElementGuid>bfdf3eb0-c8bd-42fa-9b76-4a0038ffdf6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'RESTRUCTURING FOR COVIDReport of Rejected Restructuring Covid 19View IM Restructuring' or . = 'RESTRUCTURING FOR COVIDReport of Rejected Restructuring Covid 19View IM Restructuring')]</value>
      <webElementGuid>24d5ab56-6e77-4cd4-a973-728898eb30e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
