<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Report ViewList Approved CAMList CAM by _b40749</name>
   <tag></tag>
   <elementGuidId>0229577e-6d73-4c47-836f-c4f98261a858</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='treemenu2']/li/ul/li[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f416c2cf-4fdf-4276-bf8e-4707b48d8748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submenu</value>
      <webElementGuid>1e2158e2-6187-436d-864f-572bc2b454fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Report/ ViewList Approved CAMList CAM by Customer/ GroupList CAM by Approval DateList CAM by ApproverList CAM by Car`s ConditionList Approved by Dealer per Disbursement DateList of Approved Bank Account CAMList Rejected CAMSummary Approved CAMCigna Monitoring Outstanding Asuransi CignaLaporan Customer CignaCommission/Incentive Payment - CompanyHistory Commission/Incentive Payment - CompanyDetail Commission/Incentive Payment - CompanyCommission/Incentive Payment - IndividualHistory Commission/Incentive Payment - IndividualDetail Commission/Incentive Payment - IndividualIncentive to 3rd Party Monthly ReportHistory Incentive to 3rd Party Monthly ReportDetail Incentive to 3rd Party Monthly ReportOthersHistory PaymentAmortization ReportUndisburse Contract</value>
      <webElementGuid>9efb8d37-4fc4-4d35-98b2-3f344ce52b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treemenu2&quot;)/li[@class=&quot;submenu&quot;]/ul[1]/li[@class=&quot;submenu&quot;]</value>
      <webElementGuid>86b2a342-e175-4810-8a13-59e657195cf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='treemenu2']/li/ul/li[3]</value>
      <webElementGuid>2382168a-560b-46bb-8aa1-b6a66248d69d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rejected'])[1]/following::li[1]</value>
      <webElementGuid>57e06330-7182-4d2d-a5e3-1af3e546b6b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved'])[2]/following::li[2]</value>
      <webElementGuid>200a4ef7-1ced-4064-9d36-091319914632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Report/ View']/parent::*</value>
      <webElementGuid>b21d7ffb-931d-44f7-91b9-51e961d1922a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/ul/li/ul/li[3]</value>
      <webElementGuid>949a1571-8b22-469e-8e62-9d8aa39ec96f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Report/ ViewList Approved CAMList CAM by Customer/ GroupList CAM by Approval DateList CAM by ApproverList CAM by Car`s ConditionList Approved by Dealer per Disbursement DateList of Approved Bank Account CAMList Rejected CAMSummary Approved CAMCigna Monitoring Outstanding Asuransi CignaLaporan Customer CignaCommission/Incentive Payment - CompanyHistory Commission/Incentive Payment - CompanyDetail Commission/Incentive Payment - CompanyCommission/Incentive Payment - IndividualHistory Commission/Incentive Payment - IndividualDetail Commission/Incentive Payment - IndividualIncentive to 3rd Party Monthly ReportHistory Incentive to 3rd Party Monthly ReportDetail Incentive to 3rd Party Monthly ReportOthersHistory PaymentAmortization ReportUndisburse Contract' or . = 'Report/ ViewList Approved CAMList CAM by Customer/ GroupList CAM by Approval DateList CAM by ApproverList CAM by Car`s ConditionList Approved by Dealer per Disbursement DateList of Approved Bank Account CAMList Rejected CAMSummary Approved CAMCigna Monitoring Outstanding Asuransi CignaLaporan Customer CignaCommission/Incentive Payment - CompanyHistory Commission/Incentive Payment - CompanyDetail Commission/Incentive Payment - CompanyCommission/Incentive Payment - IndividualHistory Commission/Incentive Payment - IndividualDetail Commission/Incentive Payment - IndividualIncentive to 3rd Party Monthly ReportHistory Incentive to 3rd Party Monthly ReportDetail Incentive to 3rd Party Monthly ReportOthersHistory PaymentAmortization ReportUndisburse Contract')]</value>
      <webElementGuid>216e1561-50fc-46b4-a320-0bc9e7d89ca8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
