<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select  ConsolidateGatot SubrotoBeka_9a1a4f</name>
   <tag></tag>
   <elementGuidId>597d4eea-0b0e-4dcb-b7fb-14ceb47780a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#branch_cd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='branch_cd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7bc52d8a-5d7e-4e9d-a0df-531c802f72b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>branch_cd</value>
      <webElementGuid>63f15ea8-0f1f-49bd-9ecf-145809a2f190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>branch_cd</value>
      <webElementGuid>2576c4e5-fd32-480d-b314-534480b1136d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  Select
  ConsolidateGatot SubrotoBekasiSemarangSurabayaBandungYogyakartaMedanPalembangDenpasarBalikpapan</value>
      <webElementGuid>bb031d1c-2897-4e6b-aaef-cc705a46a51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;branch_cd&quot;)</value>
      <webElementGuid>6f9f6c3b-e3e2-4daa-b0b3-f8ba730704e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJ_CAM/Page_MLCI - Credit Approval Memorandum/iframe_LOGOUT_main1</value>
      <webElementGuid>1b6f2dcb-d2b9-4093-86e5-db199af2ed77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='branch_cd']</value>
      <webElementGuid>1939fbac-cfb0-4de9-906a-0a58dde06fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch'])[1]/following::select[1]</value>
      <webElementGuid>f130912d-9066-4285-96b4-393f9d04b6c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List of Sales'])[1]/following::select[1]</value>
      <webElementGuid>8e7ace04-9043-47ae-8be7-4efa80698e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.'])[1]/preceding::select[1]</value>
      <webElementGuid>0f026429-bdbc-4975-9686-a9e76aaa44f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales No.'])[1]/preceding::select[1]</value>
      <webElementGuid>f32b63a5-2a7c-48e1-93df-ac96c7d61762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d805fae9-0fce-4be5-a2a9-b36cdec4185c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'branch_cd' and @id = 'branch_cd' and (text() = '
  Select
  ConsolidateGatot SubrotoBekasiSemarangSurabayaBandungYogyakartaMedanPalembangDenpasarBalikpapan' or . = '
  Select
  ConsolidateGatot SubrotoBekasiSemarangSurabayaBandungYogyakartaMedanPalembangDenpasarBalikpapan')]</value>
      <webElementGuid>26a79259-a0fc-4be4-a1fe-f3f206474cf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
