<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select  ConsolidateHead OfficeGatot _5c3a46</name>
   <tag></tag>
   <elementGuidId>b25f2b2b-f5d6-4745-8411-41b11e1a05a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#branch_cd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='branch_cd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e02fd1b7-754b-4ddf-97f0-2fad4fe188a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>branch_cd</value>
      <webElementGuid>21df044d-1048-4329-8aec-e1725ee18fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>branch_cd</value>
      <webElementGuid>9a09db78-8f57-4acf-aa37-8cbdff235bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  Select
  ConsolidateHead OfficeGatot SubrotoKelapa GadingPondok IndahCentral ParkSerpongAbdul MuisBekasiSemarangSurabayaBandungYogyakartaMedanPalembangDenpasarBalikpapanCorporate Finance</value>
      <webElementGuid>306f384c-b668-43df-ae41-2e16e3ef1ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;branch_cd&quot;)</value>
      <webElementGuid>b8d06ae1-d850-43b5-9163-bd802964cd33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJ_CAM/Page_MLCI - Credit Approval Memorandum/iframe_LOGOUT_main1</value>
      <webElementGuid>fff718f4-ff59-4f27-80cd-8f10ad1e65cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='branch_cd']</value>
      <webElementGuid>c4b592b6-37a8-4393-b8c2-30522fda31db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch'])[1]/following::select[1]</value>
      <webElementGuid>77c3a6ac-80fa-4479-8b87-06ccb3e8a319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List of Supplier'])[1]/following::select[1]</value>
      <webElementGuid>ac307050-77b6-4631-8c75-3227bef08f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.'])[1]/preceding::select[1]</value>
      <webElementGuid>1d850688-8154-40b7-855e-23b9c9ecc820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::select[1]</value>
      <webElementGuid>351b429d-298d-4786-ae58-3d1e869fa227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ef779e28-1a05-4e1e-bc93-de561b206b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'branch_cd' and @id = 'branch_cd' and (text() = '
  Select
  ConsolidateHead OfficeGatot SubrotoKelapa GadingPondok IndahCentral ParkSerpongAbdul MuisBekasiSemarangSurabayaBandungYogyakartaMedanPalembangDenpasarBalikpapanCorporate Finance' or . = '
  Select
  ConsolidateHead OfficeGatot SubrotoKelapa GadingPondok IndahCentral ParkSerpongAbdul MuisBekasiSemarangSurabayaBandungYogyakartaMedanPalembangDenpasarBalikpapanCorporate Finance')]</value>
      <webElementGuid>f4f3c278-a5b6-4700-ab3c-5ec4fe41a013</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
