<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select  ConsolidateGatot SubrotoBeka_9a1a4f</name>
   <tag></tag>
   <elementGuidId>e54ba44e-1226-48a3-b73b-878ef948d947</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#branch_cd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='branch_cd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>25e59422-fff4-4b35-ab43-7ab174089b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>branch_cd</value>
      <webElementGuid>dce647fe-f596-4788-a679-7382fa0ddf4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>branch_cd</value>
      <webElementGuid>3cc3124d-5634-48e4-b021-0b895271ccc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  Select
  ConsolidateGatot SubrotoBekasiSemarangSurabayaBandungYogyakartaMedanPalembangDenpasarBalikpapan</value>
      <webElementGuid>bae28280-39de-40cb-a7bb-662fd8a64f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;branch_cd&quot;)</value>
      <webElementGuid>d686f878-b9bd-4705-bf76-5b9b16258ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJ_CAM/Page_MLCI - Credit Approval Memorandum/iframe_LOGOUT_main1</value>
      <webElementGuid>6da8654e-0858-4b9c-9f92-1f4c067fbb23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='branch_cd']</value>
      <webElementGuid>0899a3ee-736c-4e27-a579-70ba1f12fc69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch'])[1]/following::select[1]</value>
      <webElementGuid>b0c653d9-f97d-4edd-9264-c50ac3f68f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List of Sales'])[1]/following::select[1]</value>
      <webElementGuid>2f359b64-c61d-471c-9b71-97e4405a76fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.'])[1]/preceding::select[1]</value>
      <webElementGuid>420fb50c-a684-4017-b07d-b1fb2d005d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales No.'])[1]/preceding::select[1]</value>
      <webElementGuid>29f553a9-6c21-4458-bec0-bc302d5aef75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d5d515b2-7fa2-4431-84ee-cdffe336718d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'branch_cd' and @id = 'branch_cd' and (text() = '
  Select
  ConsolidateGatot SubrotoBekasiSemarangSurabayaBandungYogyakartaMedanPalembangDenpasarBalikpapan' or . = '
  Select
  ConsolidateGatot SubrotoBekasiSemarangSurabayaBandungYogyakartaMedanPalembangDenpasarBalikpapan')]</value>
      <webElementGuid>508563b7-fa89-48e6-86e6-5f8168c6e516</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
