<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select  MINIBUSSEDANJEEPPICK UPLIGHT_bd4a27</name>
   <tag></tag>
   <elementGuidId>398eb418-2511-4f71-955f-ec71202ef8a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#model</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='model']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5b944bf9-7833-49a3-8848-3fdeb2c37955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>model</value>
      <webElementGuid>706fa457-d9c4-4b6f-ba98-12577fa785f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>model</value>
      <webElementGuid>387722ec-1c28-459f-9eb9-ad396d6e8061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  Select
  MINIBUSSEDANJEEPPICK UPLIGHT TRUCKTRUCKMICROBUSLAIN - LAINBUS (>30)HEAD TRACTOR/TRAILERWELDING MACHINEFLAT TOP TRAILERMOBILE ARTC. CRANETELESCOPIC BOOM LIFTMINE PUMPMODULE FUEL TRUCKSUBMERSIBLE PUMPMODULE LUBE TRUCKHYD. SUBMERSIBLE SLURRY PUMPMOTORHILUXEXCAVATORTRACTORWHEEL LOADERCRAWLER CRANEELECTRIC TOW TRUCKFORKLIFTBATTERYTELEHANDLERDUMP TRUCKLED SCREENLIFT TRUCKBUGGY CARTROUGH MOWERREACH TRUCKROTARY DRILLING RIGTRIPLE TRAILERSSYNC HOIST SYSTEMSLAB MEDIANAUTO HI CAPACITY SYSNETWORK EQUIPMENTASPHALT PAVERGENSETMULTIBALERSOLOMIXFORAGE HARVESTERBOOM LIFTTERRAIN CRANEROTARY SCREWFILTERHARDWARE SOFTWAREWHEEL DOZERBACKHOE LOADERCRANERECTIFIERGENERATORRACKING ORBITALEFP (CAMERA SYSTEM)CHILLERSOUND SYSTEMACCOUSTIC STUDIOLIGHTINGESCALATORPELLET EQUIPMENTTOWER CRANEWINDER MACHINETRACKED TROMMELBLASTHOLE DRILLSSHIP EQUIPMENTINTERIOR FIT OUTMACHINERYMOTOR GRADERCRAWLER DOZERTROMMEL SCREENARTC. DUMP TRUCKBULLDOZERVESSELHEAD ENDANTENNAIMPACT CRUSHERSHAFT RECLAIMERXPRO COAL CATTRANSMITTER 3 KW RMSTRANSMITTER 1 KWPOWER SCALEREAKTIVITAS SIARANTRANSMITTER 10 KWIRD SD/HD REACHSTAKERASPHALT MIXING PLANTVIBRATORY COMPACTOROFF HIGHWAY TRUCKPRIME PUMPSKID-STEER LOADERSFUEL TANK 20KLWATER TANK 20KLSD COMPACTORSELECTRIC BOOMLIFT</value>
      <webElementGuid>798d94b0-fb39-4b21-b921-7b8c736376b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;model&quot;)</value>
      <webElementGuid>e7b8d436-c26f-43e5-a157-ef1f40000622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJ_CAM/Page_MLCI - Credit Approval Memorandum/iframe_LOGOUT_main1</value>
      <webElementGuid>f8bd76f6-99c1-48f8-b4ca-28fd3707a4b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='model']</value>
      <webElementGuid>f982cd01-3d3b-49a5-b650-79d7b08d379a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model'])[1]/following::select[1]</value>
      <webElementGuid>dc0e55d4-b6b4-418f-85da-65b49c0f65c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[1]/following::select[2]</value>
      <webElementGuid>c40ced91-8a82-40d1-83fb-e7af142050be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.'])[1]/preceding::select[1]</value>
      <webElementGuid>33b84751-cde1-4c17-8669-e4013e2673f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[2]/preceding::select[1]</value>
      <webElementGuid>5065ae1c-d7f3-4eab-b0a1-b6aa76e166d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/select</value>
      <webElementGuid>e2f57cc3-61f8-488d-8294-92b3330c74bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'model' and @id = 'model' and (text() = '
  Select
  MINIBUSSEDANJEEPPICK UPLIGHT TRUCKTRUCKMICROBUSLAIN - LAINBUS (>30)HEAD TRACTOR/TRAILERWELDING MACHINEFLAT TOP TRAILERMOBILE ARTC. CRANETELESCOPIC BOOM LIFTMINE PUMPMODULE FUEL TRUCKSUBMERSIBLE PUMPMODULE LUBE TRUCKHYD. SUBMERSIBLE SLURRY PUMPMOTORHILUXEXCAVATORTRACTORWHEEL LOADERCRAWLER CRANEELECTRIC TOW TRUCKFORKLIFTBATTERYTELEHANDLERDUMP TRUCKLED SCREENLIFT TRUCKBUGGY CARTROUGH MOWERREACH TRUCKROTARY DRILLING RIGTRIPLE TRAILERSSYNC HOIST SYSTEMSLAB MEDIANAUTO HI CAPACITY SYSNETWORK EQUIPMENTASPHALT PAVERGENSETMULTIBALERSOLOMIXFORAGE HARVESTERBOOM LIFTTERRAIN CRANEROTARY SCREWFILTERHARDWARE SOFTWAREWHEEL DOZERBACKHOE LOADERCRANERECTIFIERGENERATORRACKING ORBITALEFP (CAMERA SYSTEM)CHILLERSOUND SYSTEMACCOUSTIC STUDIOLIGHTINGESCALATORPELLET EQUIPMENTTOWER CRANEWINDER MACHINETRACKED TROMMELBLASTHOLE DRILLSSHIP EQUIPMENTINTERIOR FIT OUTMACHINERYMOTOR GRADERCRAWLER DOZERTROMMEL SCREENARTC. DUMP TRUCKBULLDOZERVESSELHEAD ENDANTENNAIMPACT CRUSHERSHAFT RECLAIMERXPRO COAL CATTRANSMITTER 3 KW RMSTRANSMITTER 1 KWPOWER SCALEREAKTIVITAS SIARANTRANSMITTER 10 KWIRD SD/HD REACHSTAKERASPHALT MIXING PLANTVIBRATORY COMPACTOROFF HIGHWAY TRUCKPRIME PUMPSKID-STEER LOADERSFUEL TANK 20KLWATER TANK 20KLSD COMPACTORSELECTRIC BOOMLIFT' or . = '
  Select
  MINIBUSSEDANJEEPPICK UPLIGHT TRUCKTRUCKMICROBUSLAIN - LAINBUS (>30)HEAD TRACTOR/TRAILERWELDING MACHINEFLAT TOP TRAILERMOBILE ARTC. CRANETELESCOPIC BOOM LIFTMINE PUMPMODULE FUEL TRUCKSUBMERSIBLE PUMPMODULE LUBE TRUCKHYD. SUBMERSIBLE SLURRY PUMPMOTORHILUXEXCAVATORTRACTORWHEEL LOADERCRAWLER CRANEELECTRIC TOW TRUCKFORKLIFTBATTERYTELEHANDLERDUMP TRUCKLED SCREENLIFT TRUCKBUGGY CARTROUGH MOWERREACH TRUCKROTARY DRILLING RIGTRIPLE TRAILERSSYNC HOIST SYSTEMSLAB MEDIANAUTO HI CAPACITY SYSNETWORK EQUIPMENTASPHALT PAVERGENSETMULTIBALERSOLOMIXFORAGE HARVESTERBOOM LIFTTERRAIN CRANEROTARY SCREWFILTERHARDWARE SOFTWAREWHEEL DOZERBACKHOE LOADERCRANERECTIFIERGENERATORRACKING ORBITALEFP (CAMERA SYSTEM)CHILLERSOUND SYSTEMACCOUSTIC STUDIOLIGHTINGESCALATORPELLET EQUIPMENTTOWER CRANEWINDER MACHINETRACKED TROMMELBLASTHOLE DRILLSSHIP EQUIPMENTINTERIOR FIT OUTMACHINERYMOTOR GRADERCRAWLER DOZERTROMMEL SCREENARTC. DUMP TRUCKBULLDOZERVESSELHEAD ENDANTENNAIMPACT CRUSHERSHAFT RECLAIMERXPRO COAL CATTRANSMITTER 3 KW RMSTRANSMITTER 1 KWPOWER SCALEREAKTIVITAS SIARANTRANSMITTER 10 KWIRD SD/HD REACHSTAKERASPHALT MIXING PLANTVIBRATORY COMPACTOROFF HIGHWAY TRUCKPRIME PUMPSKID-STEER LOADERSFUEL TANK 20KLWATER TANK 20KLSD COMPACTORSELECTRIC BOOMLIFT')]</value>
      <webElementGuid>04261c46-ec2c-4e34-9c2c-35bb5d1f3a77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
