<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select  ABBAGRONICAIRMANALDENAAlfa R_a6d04e</name>
   <tag></tag>
   <elementGuidId>ba097341-fc62-4689-82f3-4a4e248b7291</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#brand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='brand']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b9189194-1763-44d6-bde4-3b7cc5b2de72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>brand</value>
      <webElementGuid>ba39f709-7432-45c7-a0a7-f4f5b23ab5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>brand</value>
      <webElementGuid>c7fd26c0-f127-422d-9336-ac8cda4003c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  Select
  ABBAGRONICAIRMANALDENAAlfa RomeoAMPANFOAston MartinATLAS COPCOAudiBBABEKISTINGBELKINBELLBentleyBimantaraBMWBOBCATBOMAGBOWENBTCadillacCANONCARRIERCASECATERPILLARCheryChevroletChryslerCIMCIPTA CITRA BIKACISCOCitroenCLIVETCLUB CARCOMBITOOLContainerCUMMINSCYDDaewoDaihatsuDaimlerDatsunDEXINGDFSKDHPDIAFDINGLIDodgeDOOSANDRAGFLOWDYBSISEFFERENERPACEVSF5 Network IncFDSPFerrariFiatFordFotonFURUKAWAFUSHUNFUWAGDGeelyGemalaGENIEGMCGROVEGUANGZOU DONGSU PETROLEUM DZEHAMMHANG CHAHANTAHarley DavidsonHARTECHHAULOTTEHeliHIABHinoHITACHIHITACHI SUMITOMOHOISTHondaHPHPEHummerHYSTERHyundaiIBMIHI KATOINDOCELL PRIMAInfinitiINGERSOLL RANDINOVEXINTERIOR FIT OUTIRDIsuzuIVECOJaguarJCBJeepJETJLGJOHN DEEREJOSTJUMBOKAI MEIKATOKIAKOBELCOKOMATSUKONEKONECRANEKRAUSS MAFEIKTMKUBOTA MINIKWIET POWERLamborghiniLand RoverLEMOLENOVOLexusLGLIEBHERRLIGHTSKYLINDELIUGONGLotusM-ITECHMABMACHINERYMackMANManitouMaseratiMazdaMcLarenmctMDSMercedes BenzMFMILLERMinicooperMitsubishiMORI SEIKIMorrisMorris GarageMULTIFLONECNEWLASTNEXWAVENFLGNHLNICHIYUNissanNOVA FRINGOOpelPACKSYS GLOBALPATRIAPERKINSPeugeotPorschePOTAINProtonRange RoverRAYMONDRenaultROHDE &amp; SCHWARZRolls RoyceRONGLI JIXIESaabSAKAISamsungSANDVIKSANY PALFINGERScaniaSCOMI OIL TOOLSSHACMANSHEN YANGSHINDAIWASICHUAN HONGHUASJ PETROSkodaSmartSsangyongSSBSTILLSubaruSUMITOMOSuzukiSYESTADANOTATATCMTEREX     TEREX FINLAYTEREX FRANNATeslaTimorTire Roller SAKAI TS205TOROToyotaTRIATRATRIOLIETTWIN TURRETUD NissanUD TRUCKSUNICVARCOVolks WagenVolvoWESTCOWeststarWPWranglerWulingX-RITEXCMGXJYALEYAMAHAYANMARZeleZOOMLIONZTE</value>
      <webElementGuid>89a61a37-23c1-44d1-b5b4-f3cf7d112d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brand&quot;)</value>
      <webElementGuid>c73a0575-de3a-4214-97a4-0fd5c661ab9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJ_CAM/Page_MLCI - Credit Approval Memorandum/iframe_LOGOUT_main1</value>
      <webElementGuid>28302a21-c691-4e6b-863c-4db6d34d2d90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='brand']</value>
      <webElementGuid>2d128987-21fe-44cc-9ea5-826f4df7abba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[1]/following::select[1]</value>
      <webElementGuid>531d7995-e0da-4721-8e91-fb576cfd6c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List of Brand'])[1]/following::select[1]</value>
      <webElementGuid>959dabcd-b44c-4843-90c3-61a731af5a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model'])[1]/preceding::select[1]</value>
      <webElementGuid>801fc72b-cd92-4686-9202-f0cffeeb96eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.'])[1]/preceding::select[2]</value>
      <webElementGuid>4e197658-c84e-433f-987a-f6c60e692f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ba52f2b8-2ab4-42e8-86e7-c224b8cad48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'brand' and @id = 'brand' and (text() = '
  Select
  ABBAGRONICAIRMANALDENAAlfa RomeoAMPANFOAston MartinATLAS COPCOAudiBBABEKISTINGBELKINBELLBentleyBimantaraBMWBOBCATBOMAGBOWENBTCadillacCANONCARRIERCASECATERPILLARCheryChevroletChryslerCIMCIPTA CITRA BIKACISCOCitroenCLIVETCLUB CARCOMBITOOLContainerCUMMINSCYDDaewoDaihatsuDaimlerDatsunDEXINGDFSKDHPDIAFDINGLIDodgeDOOSANDRAGFLOWDYBSISEFFERENERPACEVSF5 Network IncFDSPFerrariFiatFordFotonFURUKAWAFUSHUNFUWAGDGeelyGemalaGENIEGMCGROVEGUANGZOU DONGSU PETROLEUM DZEHAMMHANG CHAHANTAHarley DavidsonHARTECHHAULOTTEHeliHIABHinoHITACHIHITACHI SUMITOMOHOISTHondaHPHPEHummerHYSTERHyundaiIBMIHI KATOINDOCELL PRIMAInfinitiINGERSOLL RANDINOVEXINTERIOR FIT OUTIRDIsuzuIVECOJaguarJCBJeepJETJLGJOHN DEEREJOSTJUMBOKAI MEIKATOKIAKOBELCOKOMATSUKONEKONECRANEKRAUSS MAFEIKTMKUBOTA MINIKWIET POWERLamborghiniLand RoverLEMOLENOVOLexusLGLIEBHERRLIGHTSKYLINDELIUGONGLotusM-ITECHMABMACHINERYMackMANManitouMaseratiMazdaMcLarenmctMDSMercedes BenzMFMILLERMinicooperMitsubishiMORI SEIKIMorrisMorris GarageMULTIFLONECNEWLASTNEXWAVENFLGNHLNICHIYUNissanNOVA FRINGOOpelPACKSYS GLOBALPATRIAPERKINSPeugeotPorschePOTAINProtonRange RoverRAYMONDRenaultROHDE &amp; SCHWARZRolls RoyceRONGLI JIXIESaabSAKAISamsungSANDVIKSANY PALFINGERScaniaSCOMI OIL TOOLSSHACMANSHEN YANGSHINDAIWASICHUAN HONGHUASJ PETROSkodaSmartSsangyongSSBSTILLSubaruSUMITOMOSuzukiSYESTADANOTATATCMTEREX     TEREX FINLAYTEREX FRANNATeslaTimorTire Roller SAKAI TS205TOROToyotaTRIATRATRIOLIETTWIN TURRETUD NissanUD TRUCKSUNICVARCOVolks WagenVolvoWESTCOWeststarWPWranglerWulingX-RITEXCMGXJYALEYAMAHAYANMARZeleZOOMLIONZTE' or . = '
  Select
  ABBAGRONICAIRMANALDENAAlfa RomeoAMPANFOAston MartinATLAS COPCOAudiBBABEKISTINGBELKINBELLBentleyBimantaraBMWBOBCATBOMAGBOWENBTCadillacCANONCARRIERCASECATERPILLARCheryChevroletChryslerCIMCIPTA CITRA BIKACISCOCitroenCLIVETCLUB CARCOMBITOOLContainerCUMMINSCYDDaewoDaihatsuDaimlerDatsunDEXINGDFSKDHPDIAFDINGLIDodgeDOOSANDRAGFLOWDYBSISEFFERENERPACEVSF5 Network IncFDSPFerrariFiatFordFotonFURUKAWAFUSHUNFUWAGDGeelyGemalaGENIEGMCGROVEGUANGZOU DONGSU PETROLEUM DZEHAMMHANG CHAHANTAHarley DavidsonHARTECHHAULOTTEHeliHIABHinoHITACHIHITACHI SUMITOMOHOISTHondaHPHPEHummerHYSTERHyundaiIBMIHI KATOINDOCELL PRIMAInfinitiINGERSOLL RANDINOVEXINTERIOR FIT OUTIRDIsuzuIVECOJaguarJCBJeepJETJLGJOHN DEEREJOSTJUMBOKAI MEIKATOKIAKOBELCOKOMATSUKONEKONECRANEKRAUSS MAFEIKTMKUBOTA MINIKWIET POWERLamborghiniLand RoverLEMOLENOVOLexusLGLIEBHERRLIGHTSKYLINDELIUGONGLotusM-ITECHMABMACHINERYMackMANManitouMaseratiMazdaMcLarenmctMDSMercedes BenzMFMILLERMinicooperMitsubishiMORI SEIKIMorrisMorris GarageMULTIFLONECNEWLASTNEXWAVENFLGNHLNICHIYUNissanNOVA FRINGOOpelPACKSYS GLOBALPATRIAPERKINSPeugeotPorschePOTAINProtonRange RoverRAYMONDRenaultROHDE &amp; SCHWARZRolls RoyceRONGLI JIXIESaabSAKAISamsungSANDVIKSANY PALFINGERScaniaSCOMI OIL TOOLSSHACMANSHEN YANGSHINDAIWASICHUAN HONGHUASJ PETROSkodaSmartSsangyongSSBSTILLSubaruSUMITOMOSuzukiSYESTADANOTATATCMTEREX     TEREX FINLAYTEREX FRANNATeslaTimorTire Roller SAKAI TS205TOROToyotaTRIATRATRIOLIETTWIN TURRETUD NissanUD TRUCKSUNICVARCOVolks WagenVolvoWESTCOWeststarWPWranglerWulingX-RITEXCMGXJYALEYAMAHAYANMARZeleZOOMLIONZTE')]</value>
      <webElementGuid>6d0d4d69-16b9-48a8-b7db-28e304a2a920</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
