<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_CAMOn ProcessOn HandIn ProgressApprovedB_84b0b8</name>
   <tag></tag>
   <elementGuidId>25141d3b-8bf1-41cf-b0c6-3f60204641a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#treemenu2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='treemenu2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>cad236e3-be6a-497c-a458-7bec8ed1352a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>treemenu2</value>
      <webElementGuid>3f05da72-582b-454b-a048-ed0267d4412d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>treeview</value>
      <webElementGuid>3957d5af-d80f-47fe-b93b-6fa0881e64a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
CAMOn ProcessOn HandIn ProgressApprovedBank AccountsOn HandIn ProgressApprovedRejectedReport/ ViewList Approved CAMList CAM by Customer/ GroupList CAM by Approval DateList CAM by ApproverList CAM by Car`s ConditionList Approved by Dealer per Disbursement DateList of Approved Bank Account CAMList Rejected CAMSummary Approved CAMCigna Monitoring Outstanding Asuransi CignaLaporan Customer CignaCommission/Incentive Payment - CompanyHistory Commission/Incentive Payment - CompanyDetail Commission/Incentive Payment - CompanyCommission/Incentive Payment - IndividualHistory Commission/Incentive Payment - IndividualDetail Commission/Incentive Payment - IndividualIncentive to 3rd Party Monthly ReportHistory Incentive to 3rd Party Monthly ReportDetail Incentive to 3rd Party Monthly ReportOthersHistory PaymentAmortization ReportUndisburse ContractRESTRUCTURING FOR COVIDReport of Rejected Restructuring Covid 19View IM RestructuringAPPROVER AVAILABILITYOperationBranch ManagerCredit CommiteeCredit Reviewer RequestCredit Reviewer Head RequestOFFERING LETTERInput Offering LetterMASTER DATASalesSalesList of SalesDealerDealerList of SupplierDealer ProfileCollateral ObjectModelKaroseriBrand - TypeList of BrandList of ModelList of KaroseriInsuranceInsuranceList of InsuranceGROUPEntry &amp; EditGroup ReportList of GroupWATCHLISTEntry &amp; EditReport/ ViewEntry &amp; Edit by CorsecBLACKLISTEntry &amp; EditReport/ViewList Pelaporan Terduga TerorisPEPViewReportHIGH RISK CUSTOMER APU PPTVIEWREPORTSID ReportSummary SID ReportDetail SID ReportIndustry CodeINTERNAL MEMORANDUM</value>
      <webElementGuid>c44c8143-c29c-4709-bade-a57340a248a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treemenu2&quot;)</value>
      <webElementGuid>0d619833-3054-479d-8846-8ebac59cfc96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='treemenu2']</value>
      <webElementGuid>d6f99532-8577-4a19-ba9b-dae87539297c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul</value>
      <webElementGuid>a089229d-b730-4c31-a60c-54442172c88a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'treemenu2' and (text() = '
CAMOn ProcessOn HandIn ProgressApprovedBank AccountsOn HandIn ProgressApprovedRejectedReport/ ViewList Approved CAMList CAM by Customer/ GroupList CAM by Approval DateList CAM by ApproverList CAM by Car`s ConditionList Approved by Dealer per Disbursement DateList of Approved Bank Account CAMList Rejected CAMSummary Approved CAMCigna Monitoring Outstanding Asuransi CignaLaporan Customer CignaCommission/Incentive Payment - CompanyHistory Commission/Incentive Payment - CompanyDetail Commission/Incentive Payment - CompanyCommission/Incentive Payment - IndividualHistory Commission/Incentive Payment - IndividualDetail Commission/Incentive Payment - IndividualIncentive to 3rd Party Monthly ReportHistory Incentive to 3rd Party Monthly ReportDetail Incentive to 3rd Party Monthly ReportOthersHistory PaymentAmortization ReportUndisburse ContractRESTRUCTURING FOR COVIDReport of Rejected Restructuring Covid 19View IM RestructuringAPPROVER AVAILABILITYOperationBranch ManagerCredit CommiteeCredit Reviewer RequestCredit Reviewer Head RequestOFFERING LETTERInput Offering LetterMASTER DATASalesSalesList of SalesDealerDealerList of SupplierDealer ProfileCollateral ObjectModelKaroseriBrand - TypeList of BrandList of ModelList of KaroseriInsuranceInsuranceList of InsuranceGROUPEntry &amp; EditGroup ReportList of GroupWATCHLISTEntry &amp; EditReport/ ViewEntry &amp; Edit by CorsecBLACKLISTEntry &amp; EditReport/ViewList Pelaporan Terduga TerorisPEPViewReportHIGH RISK CUSTOMER APU PPTVIEWREPORTSID ReportSummary SID ReportDetail SID ReportIndustry CodeINTERNAL MEMORANDUM' or . = '
CAMOn ProcessOn HandIn ProgressApprovedBank AccountsOn HandIn ProgressApprovedRejectedReport/ ViewList Approved CAMList CAM by Customer/ GroupList CAM by Approval DateList CAM by ApproverList CAM by Car`s ConditionList Approved by Dealer per Disbursement DateList of Approved Bank Account CAMList Rejected CAMSummary Approved CAMCigna Monitoring Outstanding Asuransi CignaLaporan Customer CignaCommission/Incentive Payment - CompanyHistory Commission/Incentive Payment - CompanyDetail Commission/Incentive Payment - CompanyCommission/Incentive Payment - IndividualHistory Commission/Incentive Payment - IndividualDetail Commission/Incentive Payment - IndividualIncentive to 3rd Party Monthly ReportHistory Incentive to 3rd Party Monthly ReportDetail Incentive to 3rd Party Monthly ReportOthersHistory PaymentAmortization ReportUndisburse ContractRESTRUCTURING FOR COVIDReport of Rejected Restructuring Covid 19View IM RestructuringAPPROVER AVAILABILITYOperationBranch ManagerCredit CommiteeCredit Reviewer RequestCredit Reviewer Head RequestOFFERING LETTERInput Offering LetterMASTER DATASalesSalesList of SalesDealerDealerList of SupplierDealer ProfileCollateral ObjectModelKaroseriBrand - TypeList of BrandList of ModelList of KaroseriInsuranceInsuranceList of InsuranceGROUPEntry &amp; EditGroup ReportList of GroupWATCHLISTEntry &amp; EditReport/ ViewEntry &amp; Edit by CorsecBLACKLISTEntry &amp; EditReport/ViewList Pelaporan Terduga TerorisPEPViewReportHIGH RISK CUSTOMER APU PPTVIEWREPORTSID ReportSummary SID ReportDetail SID ReportIndustry CodeINTERNAL MEMORANDUM')]</value>
      <webElementGuid>8b531551-377f-4e68-99e3-e5e8990677fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
