<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>01ab3c6f-ab65-4844-a3fc-46e2b8acecbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='main.setLogout();'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.nav-item > a.nav-link.fa.fa-sign-out</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f1b78d1-f9aa-4bef-8a63-0c378f19b3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link fa fa-sign-out</value>
      <webElementGuid>10adc5d6-65d6-41b6-bda0-333339a482d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>75f1735c-288c-4961-ab56-0e2adec5ba3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>main.setLogout();</value>
      <webElementGuid>ba6b4d0b-661c-4b98-8ab1-c0c3353b1f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Logout</value>
      <webElementGuid>949b1377-6a46-4dfe-854e-1a84a8a8f54c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/ul[@class=&quot;navbar-nav mr-0&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link fa fa-sign-out&quot;]</value>
      <webElementGuid>e5218eb7-15be-4827-904d-336c71d1918e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='main.setLogout();'])[2]</value>
      <webElementGuid>6d1881da-9a88-4603-8162-68a2f74a0ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/ul[5]/li[2]/a</value>
      <webElementGuid>10257ea3-96f7-49da-9d46-1bb1378591d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Logout')])[2]</value>
      <webElementGuid>fb9e2ddd-9aa9-4b4c-baa2-d75dad7f34a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rights: Regular User'])[1]/following::a[3]</value>
      <webElementGuid>7a4e0032-454f-4f41-8505-e494888c8de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DB: DB-DEV.mitsuilease.co.id\Data00Dev_211004'])[1]/following::a[3]</value>
      <webElementGuid>ec6d2769-97f4-4d32-9358-7088df95d7b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Core Application'])[1]/preceding::a[1]</value>
      <webElementGuid>3c2d1810-5bd0-4030-9802-5142e00a9579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>3988d43c-0c3d-4ab8-8d1a-772b2dc2aa9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>a684f813-c069-499c-a095-f14556836c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = ' Logout' or . = ' Logout')]</value>
      <webElementGuid>1a21be0a-babf-4baf-a2c9-50df1c609372</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
