<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Beginning_Balance_1</name>
   <tag></tag>
   <elementGuidId>15ecae5b-2726-4b0c-afec-4ae0db5d85f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#begbal\[0\]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
