<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Calculate_1</name>
   <tag></tag>
   <elementGuidId>2e74751c-9148-4319-9fb4-7d76578d88a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calculates\[0\]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
