<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Credit_1</name>
   <tag></tag>
   <elementGuidId>0cb5cb85-def8-4fb4-82f3-8220e4cec93d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#credit\[0\]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
