<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Debit_1</name>
   <tag></tag>
   <elementGuidId>805ca578-58fe-424d-a31e-0cfac642ee21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#debet\[0\]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
