<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ending_Balance_1</name>
   <tag></tag>
   <elementGuidId>c57ed59d-ef2a-4948-a128-09cb2c312f2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#endbal\[0\]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
