<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Month_1</name>
   <tag></tag>
   <elementGuidId>d55bb20f-b1bd-4ff4-9e35-61e113f5b395</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bln\[0\]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
