<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Year_1</name>
   <tag></tag>
   <elementGuidId>89f0058d-feed-477a-8e94-020e0179ad33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#thn\[0\]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
