<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Calculate_Button</name>
   <tag></tag>
   <elementGuidId>a542edd9-5fd2-4383-81dd-003b2dc27db5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calculates\[0\]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@value='Calculate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
