<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Document_Number_Label</name>
   <tag></tag>
   <elementGuidId>aee57a0b-cb36-46bc-a796-66dffcfe5caa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.judul1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
